import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { DatabaseSync, type SQLInputValue } from "node:sqlite";
import test, { type TestContext } from "node:test";
import { buildTarotSeed } from "../db/tarot-seed";
import { buildTarotReadingInput } from "../lib/tarot-reading-context";
import { getTarotRepository } from "../lib/tarot-repository";
import { buildSpreadCatalogMigrationSql } from "../scripts/generate-tarot-seed";

const relationshipTemplateId = "spread-relationships-relationship-check-in";
const canonicalPositions = [
  { id: `${relationshipTemplateId}-us_right_now`, legacyId: `${relationshipTemplateId}-you`, key: "us_right_now", order: 0 },
  { id: `${relationshipTemplateId}-needs_work`, legacyId: `${relationshipTemplateId}-connection`, key: "needs_work", order: 1 },
  { id: `${relationshipTemplateId}-can_help`, legacyId: `${relationshipTemplateId}-them`, key: "can_help", order: 2 },
] as const;

const migration = (name: string) => readFileSync(new URL(`../drizzle/${name}`, import.meta.url), "utf8");

function database(t: TestContext) {
  const sqlite = new DatabaseSync(":memory:");
  t.after(() => sqlite.close());
  sqlite.exec(migration("0001_dynamic_tarot.sql"));
  sqlite.exec(migration("0002_tarot_seed.sql"));
  return sqlite;
}

test("0004 adds the nullable normalized reading payload column", (t) => {
  const sqlite = database(t);
  sqlite.exec(migration("0004_reading_payload.sql"));
  const columns = sqlite.prepare("PRAGMA table_info(readings)").all() as Array<{ name: string; notnull: number }>;
  const payload = columns.find((column) => column.name === "reading_payload");
  assert.ok(payload);
  assert.equal(payload.notnull, 0);
});

function d1Database(sqlite: DatabaseSync): D1Database {
  const prepare = (sql: string) => {
    let values: SQLInputValue[] = [];
    return {
      bind(...args: SQLInputValue[]) { values = args; return this; },
      async first() { return sqlite.prepare(sql).get(...values) || null; },
      async all() { return { results: sqlite.prepare(sql).all(...values) }; },
      async run() { return sqlite.prepare(sql).run(...values); },
    };
  };
  return { prepare, batch: async (statements: ReturnType<typeof prepare>[]) => Promise.all(statements.map((statement) => statement.run())) } as unknown as D1Database;
}

function relationshipRows(sqlite: DatabaseSync) {
  return sqlite.prepare("SELECT id, position_key AS key, position_order AS 'order' FROM spread_positions WHERE spread_template_id = ? ORDER BY position_order, id")
    .all(relationshipTemplateId)
    .map((row) => ({ id: row.id, key: row.key, order: row.order }));
}

test("0001 -> 0002 -> 0003 succeeds repeatedly and keeps canonical fresh relationship positions", (t) => {
  const sqlite = database(t);
  const catalogMigration = migration("0003_moonlight_spread_catalog.sql");

  assert.doesNotThrow(() => sqlite.exec(catalogMigration));
  assert.doesNotThrow(() => sqlite.exec(catalogMigration));
  assert.deepEqual(relationshipRows(sqlite), canonicalPositions.map(({ id, key, order }) => ({ id, key, order })));
  assert.deepEqual(sqlite.prepare("PRAGMA foreign_key_check").all(), []);
});

test("the checked-in catalog migration is generated by buildSpreadCatalogMigrationSql", () => {
  const catalogMigration = migration("0003_moonlight_spread_catalog.sql");
  const timestamp = Number(catalogMigration.match(/updated_at`=(\d+)/)?.[1]);
  assert.ok(Number.isSafeInteger(timestamp));
  assert.equal(buildSpreadCatalogMigrationSql(buildTarotSeed(), timestamp), catalogMigration);
});

test("0003 preserves referenced legacy relationship IDs and stored readings remain resolvable", async (t) => {
  const sqlite = database(t);
  for (const position of canonicalPositions) {
    sqlite.prepare("UPDATE spread_positions SET id = ? WHERE id = ?").run(position.legacyId, position.id);
  }

  const categoryId = sqlite.prepare("SELECT category_id AS categoryId FROM spread_templates WHERE id = ?").get(relationshipTemplateId)!.categoryId as string;
  const cards = sqlite.prepare("SELECT id FROM tarot_cards ORDER BY display_order LIMIT 3").all() as Array<{ id: string }>;
  sqlite.prepare("INSERT INTO reading_sessions (id, user_id, guest_id, question, optional_context, category_id, spread_template_id, spread_type, card_count, locale, status, created_at, updated_at) VALUES (?, NULL, ?, ?, ?, ?, ?, ?, 3, 'en', 'drawn', 1, 1)")
    .run("legacy-relationship-reading", "legacy-owner", "What does this relationship need?", "Preserve the historical spread.", categoryId, relationshipTemplateId, "row-3");
  const insertCard = sqlite.prepare("INSERT INTO reading_cards (id, session_id, card_id, spread_position_id, position_key, position_order, position_label, orientation, card_order, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1)");
  canonicalPositions.forEach((position, index) => {
    insertCard.run(`legacy-reading-card-${index}`, "legacy-relationship-reading", cards[index].id, position.legacyId, position.key, position.order, `Legacy ${index}`, index === 1 ? "reversed" : "upright", index);
  });
  sqlite.prepare("INSERT INTO readings (id, session_id, opening, card_readings, synthesis, advice, closing, disclaimer, model_name, prompt_version, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")
    .run("legacy-reading-result", "legacy-relationship-reading", "Legacy opening", "[]", "Legacy synthesis", "Legacy advice", "Legacy closing", "Legacy disclaimer", "legacy/model", "tarot-reading-v2", 1, 1);

  const catalogMigration = migration("0003_moonlight_spread_catalog.sql");
  assert.doesNotThrow(() => sqlite.exec(catalogMigration));
  assert.doesNotThrow(() => sqlite.exec(catalogMigration));
  sqlite.exec(migration("0004_reading_payload.sql"));
  assert.equal(sqlite.prepare("SELECT reading_payload AS readingPayload FROM readings WHERE id = ?").get("legacy-reading-result")!.readingPayload, null);
  assert.deepEqual(relationshipRows(sqlite), canonicalPositions.map(({ legacyId: id, key, order }) => ({ id, key, order })));
  assert.deepEqual(sqlite.prepare("PRAGMA foreign_key_check").all(), []);

  const repository = getTarotRepository(d1Database(sqlite));
  const stored = await repository.getSessionForOwner("legacy-relationship-reading", { kind: "guest", guestId: "legacy-owner" });
  const template = await repository.getReadingTemplate(relationshipTemplateId, "en");
  assert.ok(stored);
  assert.ok(template);
  const meanings = new Map(await Promise.all(stored.cards.map(async (card) => [card.cardId, (await repository.getMeaningPair(card.cardId, "en"))!] as const)));
  const input = buildTarotReadingInput({ ...stored, template, meanings, locale: "en" });
  assert.deepEqual(input.cards.map((card) => card.position.id), canonicalPositions.map((position) => position.legacyId));
  assert.deepEqual(input.cards.map((card) => [card.position.key, card.position.order]), canonicalPositions.map((position) => [position.key, position.order]));
});
