import Logo from "@/components/brand/logo";
import { Camera, CirclePlay, Heart, Music2, Play } from "lucide-react";
import Link from "next/link";
import type { ShellVariant, Translator } from "./types";

export default function NaTarotFooter({ variant, t }: { variant: ShellVariant; t: Translator }) {
  if (variant === "library") return <footer className="guidebook-target-footer"><div className="guidebook-target-footer-brand"><Logo variant="dark" href="/" compact /><span>{t("header.tagline")}</span></div><nav aria-label={t("nav.footer")}><Link href="/guidebook">{t("auth.footerGuide")}</Link><Link href="/privacy">{t("auth.footerPrivacy")}</Link><Link href="/terms">{t("auth.footerTerms")}</Link></nav></footer>;
  if (variant === "home") return <footer className="home-footer"><div className="home-footer-brand"><Logo variant="dark" href="/" compact /><span>{t("header.tagline")}</span></div><nav className="home-footer-links" aria-label={t("home.footerLinks")}><Link href="/guidebook">{t("home.explore")}</Link><Link href="/privacy">{t("home.privacy")}</Link><Link href="/terms">{t("home.terms")}</Link></nav><div className="home-footer-socials" aria-hidden="true"><span><Heart size={17} /></span><span><Play size={16} /></span><span><Camera size={17} /></span><span><Music2 size={17} /></span></div></footer>;
  if (variant === "practice") return <footer className="practice-v1-footer"><Logo variant="dark" href="/" compact /><span className="practice-v1-footer-tagline">{t("header.tagline")}</span><nav className="practice-v1-footer-links"><Link href="/guidebook">{t("home.guidebook")}</Link><Link href="/privacy">{t("footer.privacy")}</Link><Link href="/terms">{t("footer.terms")}</Link></nav><div className="practice-v1-socials" aria-label="Social links"><span aria-label={t("footer.facebook")}><b className="practice-v1-social-letter" aria-hidden="true">f</b></span><span aria-label={t("footer.youtube")}><CirclePlay size={18} strokeWidth={1.35} /></span><span aria-label={t("footer.instagram")}><Camera size={18} strokeWidth={1.35} /></span><span aria-label={t("footer.tiktok")}><Music2 size={18} strokeWidth={1.35} /></span></div></footer>;
  if (variant === "affiliate") return <footer className="affiliate-footer"><Logo variant="dark" href="/" compact /><span className="affiliate-footer-tagline">{t("header.tagline")}</span><div className="affiliate-footer-links"><Link href="/guidebook">{t("home.guidebook")}</Link><Link href="/privacy">{t("footer.privacy")}</Link><Link href="/terms">{t("footer.terms")}</Link></div></footer>;
  if (variant === "membership") return <footer className="membership-footer"><Logo variant="dark" href="/" compact /><span className="membership-footer-tagline">{t("header.tagline")}</span><nav><Link href="/guidebook">{t("home.guidebook")}</Link><Link href="/privacy">{t("footer.privacy")}</Link><Link href="/terms">{t("footer.terms")}</Link></nav><div className="membership-footer-socials" aria-label="Social links"><span aria-label={t("footer.facebook")}><b aria-hidden="true">f</b></span><span aria-label={t("footer.youtube")}><Play size={17} strokeWidth={1.4} /></span><span aria-label={t("footer.instagram")}><Camera size={17} strokeWidth={1.4} /></span><span aria-label={t("footer.tiktok")}><Music2 size={17} strokeWidth={1.4} /></span></div></footer>;
  return <footer><Logo variant="dark" href="/" compact /><div className="marquee"><span>{t("home.welcome").repeat(8)}</span></div><Link href="/guidebook">{t("home.guidebook")}</Link><Link href="/privacy">{t("footer.privacy")}</Link><Link href="/terms">{t("footer.terms")}</Link></footer>;
}
